clc; clear;

diary('logfile.txt'); diary on;

%% 1. Create/load environment
env = createEnvironment();

%% 2. Load existing agent (from .mat)
loadedData = load('Agent600.mat', 'agent');
agent = loadedData.agent;

%% 3. Set new or continued training options
maxSteps = 1000;
trainOpts = rlTrainingOptions( ...
    "MaxEpisodes", 1600, ...
    "MaxStepsPerEpisode", maxSteps, ...
    "ScoreAveragingWindowLength",20, ...
    "StopTrainingCriteria","AverageReward", ...
    "StopTrainingValue",5000, ...
    "SaveAgentCriteria","EpisodeFrequency", ...
    "SaveAgentValue",200, ...
    "SaveAgentDirectory","agents", ...
    "Verbose",true, ...
    "Plots","training-progress");

%% 4. Continue training from previous state
trainingStats = train(agent, env, trainOpts);

save("Agent.mat", "agent")   % Optionally save after further training
diary off;
